version: '2'
services:
  grafana:
    image: appcelerator/grafana:grafana-3.1
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  influxdb:
    image: influxdb:1.0.2-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
      - "./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
  telegraf:
    image: telegraf:1.0.1-alpine
    depends_on:
      - "influxdb"
    ports:
      - "8125:8125/udp"
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
volumes:
  influxdb:
    driver: local
  grafana:
    driver: local
