version: '2'
services:
  grafana:
    image: adipirro852/grafana:alpine
    ports:
      - "3000:3000"
  influxdb:
    image: influxdb:alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
      - "./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
  telegraf:
    image: telegraf:alpine
    depends_on:
      - "influxdb"
    ports:
      - "8125:8125/udp"
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
volumes:
  influxdb:
    driver: local
  grafana:
    driver: local
